export const CONNECT_WALLET = "CONNECT_WALLET";
export const LOAD_MAIN_CONTRACT = "LOAD_MAIN_CONTRACT";
export const LOAD_MARKETS = "LOAD_MARKETS";
export const LOAD_MARKETS_ACCOUNT = "LOAD_MARKETS_ACCOUNT";
export const LOAD_MARKET_SHOW = "LOAD_MARKET_SHOW";
export const CLEAR_LOADED_MARKET = "CLEAR_LOADED_MARKET";
